name: EventSystem
version: ${project.version}
main: me.gong.eventsystem.EventSystem
commands:
  host:
    default: op
  endevent:
    aliases: [ende]
    default: op
  setup:
    default: op
  task:
    default: op
  join:
    aliases: [j]
  quit:
    aliases: [q]
