name: EventSystem
version: ${project.version}
main: me.gong.eventsystem.EventSystem
commands:
  host:
  endevent:
    aliases: [ende]
  setup:
  task:
  join:
    aliases: [j]
  quit:
    aliases: [q]
  permissions:
   eventsystem.admin:
    description: Gives permission to use event system commands
    default: op
